/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Strict Light-Theme Monochrome Palette
        mono: {
          black: "#000000",
          nearBlack: "#0A0A0A",
          dark: "#111111",
          darkGrey: "#171717",
          charcoal: "#1C1C1C",
          grey: "#2A2A2A",
          sidebar: "#111111",
          sidebarBorder: "#262626",
          app: "#F5F5F5",
          surface: "#FFFFFF",
          surfaceSecondary: "#FAFAFA",
          surfaceHover: "#F5F5F5",
          border: "#E5E5E5",
          borderSecondary: "#D4D4D4",
          borderStrong: "#737373",
          borderDark: "#171717",
          text: "#171717",
          textSecondary: "#525252",
          muted: "#737373",
          lightGrey: "#A3A3A3",
          veryLightGrey: "#E5E5E5",
          offWhite: "#F5F5F5",
          white: "#FFFFFF",
        },
        cat: {
          app: "#F5F5F5",
          sidebar: "#111111",
          surface: "#FFFFFF",
          elevated: "#FAFAFA",
          card: "#FFFFFF",
          border: "#E5E5E5",
          'border-strong': "#737373",
          text: "#171717",
          'text-secondary': "#525252",
          muted: "#737373",
          yellow: "#111111",
          'yellow-hover': "#262626",
          'yellow-subtle': "rgba(0, 0, 0, 0.04)",
          'yellow-border': "#E5E5E5",
        },
        safety: {
          safe: "#525252",
          safeSubtle: "#FAFAFA",
          safeBorder: "#E5E5E5",
          warning: "#171717",
          warningSubtle: "#FFFFFF",
          warningBorder: "#737373",
          high: "#171717",
          highSubtle: "#F5F5F5",
          highBorder: "#171717",
          critical: "#FFFFFF",
          criticalSubtle: "#111111",
          criticalBorder: "#000000",
        },
        industrial: {
          app: "#F5F5F5",
          sidebar: "#111111",
          surface: "#FFFFFF",
          elevated: "#FAFAFA",
          card: "#FFFFFF",
          border: "#E5E5E5",
          borderSubtle: "#E5E5E5",
          borderStrong: "#737373",
          text: "#171717",
          textSecondary: "#525252",
          textMuted: "#737373",
        }
      },
      borderRadius: {
        'sm': '4px',
        'md': '6px',
        'lg': '8px',
        'card': '6px',
        'pill': '9999px',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      boxShadow: {
        'subtle': '0 1px 2px 0 rgba(0, 0, 0, 0.04)',
        'drawer': '-2px 0 16px 0 rgba(0, 0, 0, 0.12)',
        'elevated': '0 4px 12px 0 rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
}
